#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr %>%
#' @importFrom dplyr across
#' @importFrom dplyr any_of
#' @importFrom dplyr as_tibble
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr coalesce
#' @importFrom dplyr data_frame
#' @importFrom dplyr distinct
#' @importFrom dplyr everything
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr last
#' @importFrom dplyr last_col
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr mutate_all
#' @importFrom dplyr mutate_at
#' @importFrom dplyr n
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr rename_with
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr tibble
#' @importFrom dplyr ungroup
#' @importFrom DT datatable
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 geom_sf
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 theme_minimal
#' @importFrom ggplot2 xlim
#' @importFrom ggplot2 ylim
#' @importFrom httr add_headers
#' @importFrom httr content
#' @importFrom httr GET
#' @importFrom httr http_error
#' @importFrom httr http_status
#' @importFrom httr POST
#' @importFrom httr timeout
#' @importFrom httr progress
#' @importFrom httr status_code
#' @importFrom httr write_disk
#' @importFrom jsonlite fromJSON
#' @importFrom jsonlite prettify
#' @importFrom jsonlite toJSON
#' @importFrom leaflet addMarkers
#' @importFrom leaflet addProviderTiles
#' @importFrom leaflet addTiles
#' @importFrom leaflet leaflet
#' @importFrom leaflet icons
#' @importFrom leaflet addAwesomeMarkers
#' @importFrom leaflet awesomeIcons
#' @importFrom leaflet providerTileOptions
#' @importFrom leaflet addCircleMarkers
#' @importFrom leaflet addCircles
#' @importFrom lifecycle badge
#' @importFrom lifecycle deprecate_stop
#' @importFrom lifecycle deprecate_warn
#' @importFrom lifecycle deprecated
#' @importFrom lifecycle is_present
#' @importFrom purrr map
#' @importFrom purrr map_df
#' @importFrom purrr map_dfr
#' @importFrom readr col_character
#' @importFrom readr cols
#' @importFrom readr locale
#' @importFrom readr read_delim
#' @importFrom readr read_tsv
#' @importFrom readr type_convert
#' @importFrom readr write_tsv
#' @importFrom readxl excel_sheets
#' @importFrom readxl read_excel
#' @importFrom readxl read_xls
#' @importFrom readxl read_xlsx
#' @importFrom sf st_area
#' @importFrom sf st_as_sf
#' @importFrom sf st_as_sfc
#' @importFrom sf st_bbox
#' @importFrom sf st_crs
#' @importFrom sf st_geometry_type
#' @importFrom sf st_intersection
#' @importFrom sf st_intersects
#' @importFrom sf st_join
#' @importFrom sf st_make_valid
#' @importFrom sf st_read
#' @importFrom sf st_set_crs
#' @importFrom sf st_transform
#' @importFrom sf st_union
#' @importFrom sf st_within
#' @importFrom sf st_wrap_dateline
#' @importFrom sp coordinates
#' @importFrom sp CRS
#' @importFrom sp over
#' @importFrom sp proj4string
#' @importFrom sp spTransform
#' @importFrom stringi stri_enc_detect
#' @importFrom terra buffer
#' @importFrom terra crs
#' @importFrom terra vect
#' @importFrom tidyr all_of
#' @importFrom tidyr drop_na
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr unnest
#' @importFrom vroom vroom
#' @importFrom worrms wm_classification
#' @importFrom worrms wm_records_taxamatch
#' @importFrom worrms wm_children
#' @importFrom worrms wm_synonyms
#' @importFrom worrms wm_name2id_
#' @importFrom worrms wm_record
#' @importFrom worrms wm_records_name
#' @importFrom worrms wm_records_names
## usethis namespace: end
NULL
